version: "3.7"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/statics
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test_secret_key
      - DEBUG=False
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A core worker -l info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
    
  beat:
    build: .
    container_name: beat
    command: celery -A core beat -l info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - celery
      - backend

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

volumes:
  static_volume:
  media_volume:
